services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: always
    volumes:
      - /volume1/docker/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    env_file:
      - .env
    volumes:
      - /volume1/docker/linkwarden/meili_data:/meili_data
