services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=linkwarden
      - POSTGRES_USER=linkwardenuser
      - POSTGRES_PASSWORD=linkwardenpass
    restart: always
    volumes:
      - /volume1/docker/linkwarden/pgdata:/var/lib/postgresql/data
  linkwarden:
    environment:
      - NEXTAUTH_URL=http://localhost:3000/api/v1/auth
      - NEXTAUTH_SECRET=lq0IEz0edzdmVSv8deKWcVcFhDzvq7AwE8cAPw6bkBMMCwqvssQsbYxd8LeWmvj0
      - DATABASE_URL=postgres://linkwardenuser:linkwardenpass@linkwarden-deploy-postgres-1:5432/linkwarden
      - POSTGRES_DB=linkwarden
      - POSTGRES_USER=linkwardenuser
      - POSTGRES_PASSWORD=linkwardenpass
      - MEILI_MASTER_KEY=${linkwardenmeilisearch}
      - MEILI_HOST=http://meilisearch:7700
      - OPENROUTER_MODEL=google/gemma-4-26b-a4b-it:free
      - OPENROUTER_API_KEY=${openrouter}
    restart: always
    image: ghcr.io/linkwarden/linkwarden:latest
    ports:
      - 3101:3000
    volumes:
      - /volume1/docker/linkwarden/data:/data/data
    depends_on:
      - postgres
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      - MEILI_MASTER_KEY=${linkwardenmeilisearch}
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - /volume1/docker/linkwarden/meili_data:/meili_data
